### ISSUE TITLE
Block malicious users

### ISSUE THREAD

**Issue by teleyinex** [Scifabric/pybossa#1159]
Sometimes, a user might want to get more and more points for the community doing a very poor job, so it might be interesting to flag that user like blocking it or ignoring it.

**Comment by dc1520** [comment]
What could be the best mechanism to block malicious users? Means, how can we flag users as blocked users in Pybossa without deleting their accounts from Pybossa?

**Comment by teleyinex** [comment]
It could be a flag in the user table that will exclude their contributions from the projects when exporting the task runs via the API or the web exporters. What do you think @dc1520 ? We could even have a flag to force the inclusion of those task runs, if the project owner wants.

**Comment by dc1520** [comment]
One of the solution could be, pybossa database to maintain the list of such users as black listed. Access to projects should be locked for such users instead of allowing them to mess up the project database with malicious responses and dishonoring such responses at the later stage of exporting task runs

**Comment by teleyinex** [comment]
Yes, that could be also part of the way of working. When a user is flagged as problematic, then it cannot access the given project. We only will need to do this per project or per full platform. I mean, usually a bad user will do harm in all the platform, right?

**Comment by teleyinex** [comment]
We're not going to develop this for the moment.
