### ISSUE TITLE
Overriding taskrun

### ISSUE THREAD

**Issue by patthai** [Scifabric/pybossa#1358]
Hello,

I have a question about overriding taskrun in Pybossa. I realized that when I re-evaluate the taskruns that I already labelled, I got the 403 error on jquery. I wonder if anyone can suggest potential solution.

![image](https://cloud.githubusercontent.com/assets/10229202/21408404/29c17aee-c792-11e6-864b-39186081ffc7.png)

Thank you,

Pat

**Comment by teleyinex** [comment]
Hi,

Yes, PYBOSSA does not allow you to participate twice in the same task. Why? Because then trolls would be able to bias the results, and we don't want that. Basically a user can only participate once in a task, and you need to get several different users to do the same task. This will ensure that you have enough observations to do an statistical analysis and get conclusions about that task.

If PYBOSSA allowed a user to modify their answers, then, we would end up in a situation where the statistics will not be valid.

Therefore, there's no workaround with the official PYBOSSA schedulers. You will need to build your own, and override the default behavior using our plugin system. Take a look into the [plugin documentation](http://docs.pybossa.com/en/latest/plugins.html?highlight=plugin).

All the best,

Daniel
