### ISSUE TITLE
Issue with webhooks: Connection refused

### ISSUE THREAD

**Issue by daksh-agarwal** [Scifabric/pybossa#1506]
I am trying to use webhooks with webhooks (enki integration) running at localhost:12345 and with the url of webhooks set at localhost:12345 on Pybossa. I am following the [blog](http://docs.pybossa.com/en/latest/install.html) to run Pybossa and [this](https://github.com/Scifabric/webhooks) webhook link to run webhooks. But, when I am running rqscheduler with redis-server port at 6379 (default) with worker to perform the scheduling jobs, I am not able to run the instance of webhooks. It gives me 'Connection Refused' error. I want to run all of this together, so test it on real-time.

**Comment by teleyinex** [comment]
Hi,

Do you need to run webhooks, the micro-service, in parallel? I mean, [do you need the background jobs for it](https://github.com/Scifabric/webhooks#configuring-background-jobs)? If the answer is not, I would suggest you just run the server without redis (I'm saying [this server](https://github.com/Scifabric/webhooks)). This will allow you to debug it.

Then, be sure that PYBOSSA actually runs background jobs, otherwise it will fail to actually run the jobs posting the data to the [webhooks server](https://github.com/Scifabric/webhooks).

**Comment by daksh-agarwal** [comment]
@teleyinex 
Sorry, I didn't get that. Yes, I want to run webhooks in parallel. As far as I understood, I need to run webhooks server without redis; but use the redis-server with Pybossa. 
I may not require background jobs. 
I have been using all these services currently, with webhooks url set as localhost:12345 on Pybossa. 

Scheduler:: rqscheduler -H 127.0.0.1 -p 6379
Worker:: python app_context_rqworker.py scheduled_jobs super high medium low email maintenance
Pybossa:: python run.py (on port 5000)
Webooks:: python app.py (on port 12345)

With SSE disabled, it is giving privatestream 404 error on webhooks, so enabled SSE. Also, removed the connection=Redis() from webhooks app.py file, so as to run server without redis. 

But, still I am not able to post anything to webhooks.

**Comment by teleyinex** [comment]
It looks like you have something wrong. SSE is only needed if you want to get updated info on the webhooks' page project without having to refresh it. Thus, SSE is not mandatory at all.

The webhooks server does not need Redis to run. You don't have to remove redis by hand. Just configure it in the settings file (as described [here](https://github.com/Scifabric/webhooks#configuring-background-jobs)).

Then, just make sure that the webhooks server is running. To test it, open your localhost:12345 and you should see the pie chart. If that's what's happening, then everything is fine.

Then, check that your project has tasks and that it has the localhost:12345 url in the webhooks setting's of that project. Actually, when you add it, the PYBOSSA server will test that your webhooks server is running. If the page does not give you any error, then the webhooks hook is configured properly.

Now: testing. For testing be sure to set a task redundancy really low. For example: 1. This will ensure that as soon as you send a task_run the server will do the POST to the webhook server, because the task has been completed. You should be able to see this action in the following page:

http://YOURPYBOSSASERVER/project/<short_name>/webhook

This should list your webhook action, and you should be able to see the errors, if any.

Thus, it should be as simple as this ;-)

**Comment by teleyinex** [comment]
Closing this. Please, open if you need more info.
