### ISSUE TITLE
Add Whoosh Searching

### ISSUE THREAD

**Issue by alexandermendes** [Scifabric/pybossa#1551]
Just an idea for now, but it would be really cool to expose searches via the API. [Flask-WhooshAlchemy](https://github.com/gyllstromk/Flask-WhooshAlchemy) looks interesting!

**Comment by teleyinex** [comment]
We've you covered :-) Or I think so, haha. I'll need to read a bit more about Whoosh but it looks like it does the same as our beloved [PostgreSQL full text search engine](https://www.postgresql.org/docs/9.5/static/textsearch.html).

Postgresql does stemming (supporting several languages) you can use dictionaries, synonyms, etc. 

All these set of features are available via the API, even inside the first level of key:value pairs of the info field.

For example, you can get all the results from our PYBOSSA server Sr. Alergeno that has the word "fruta" (fruit in Spanish) like this:

https://sralergeno.pybossa.com/api/result?info=name::fruta&fulltextsearch=1&all=1

As we're using the full text search capabilities of PostgreSQL this query will return items with the word in singular, in plural, etc. If it was a verb its conjugations, etc. It's really, really powerful.

You use the attribute: **info=** and then the key and then *::* to have the "=" symbol and the text that you want to search. It's very important to flag the server that you are doing a fulltextsearch with this flag: **fulltextsearch=1** otherwise it will try to find the exact word that you are typing. 

PYBOSSA can tell PostgreSQL which language you are searching on with this configuration:

```python
FULLTEXTSEARCH_LANGUAGE = 'english'
```

Thus, the stemming and indexing will happen properly. Thanks to these features, the possibilities are endless in terms of indexing stuff. What I love from this is that we fully rely on our own stack without having to use another library. Plus PostgreSQL does this really well :-)

Did you know about this @alexandermendes? It is in the docs, but I agree we should improve this asap so people can discover this feature ;-) (actually we are working towards making the docs much much better).

**Comment by teleyinex** [comment]
I forgot to include here the link to our docs regarding [full text search](http://docs.pybossa.com/en/latest/api.html?highlight=full%20text#full-text-search)

**Comment by alexandermendes** [comment]
Thanks! Yeah I did see the full text search stuff, but am I right in thinking that this only works for the info field (and it's sub fields)? That looks really handy for certain things, like creating some cool results pages, but it would be nice to also have a way to, for example, search for projects by partial title, or users by partial name.

There may be other ways to do this, I probably need to experiment more!

**Comment by teleyinex** [comment]
We can always extend the API to support this :-)

**Comment by alexandermendes** [comment]
Well that would be great!

**Comment by alexandermendes** [comment]
I think we can close this one, we're now just filtering in the browser where we want to implement a form of searching by name, and when the JSONB filtering is sorted out we'll have a lot more options.
