### ISSUE TITLE
How to determine user admin via API

### ISSUE THREAD

**Issue by alexandermendes** [Scifabric/pybossa#1608]
This one is more of a question than a direct issue. Via the API, how do you determine whether or not a user is an admin (and therefore can be shown links to the admin site etc.)?

I can make a second call to some other endpoint like `/api/user` and see if the `id` is present but seems like a bit of a hack! Is there anything against exposing the admin column in the user model via the API? Or how else have you dealt with this kind of thing?

**Comment by teleyinex** [comment]
We removed it from the API calls, because it could show which users are admins, and then you could start trying to attack them via the API.

In any case, once a user is authenticated, you can always get from the cookie its ID, and then, get the USER his/her user info, and that should include the admin flag. Thus, we usually have done it in this way :-) (the hacky way).

But again, not 100% sure if this is the best option. Open to discussion.

**Comment by alexandermendes** [comment]
Cool, so that's what I'm basically doing at the moment - checking for a cookie and then going and grabbing the user data from `/account/profile`. Somehow I missed that this does indeed include the admin flag! I guess I was going by the docs where the admin flag isn't actually shown anywhere, but I could've checked the response properly.

Still trying to figure out the best way to handle these sessions myself but if that's a method that you have used then at least I'm moving in the right direction!

**Comment by alexandermendes** [comment]
Nope, actually the admin flag is not added to `account/profile`, I was slotting it in elsewhere. 

I think it probably should be added to [`get_user_summary`](https://github.com/Scifabric/pybossa/blob/059ea1226903398c2ee760a626a1cfbff7bf989e/pybossa/cache/users.py#L45-L78)? That should provide a decent fix for now?
