### ISSUE TITLE
Deployment with docker and docker-compose

### ISSUE THREAD

**Issue by BonaBeavis** [Scifabric/pybossa#1670]
Hi,

are there any plans to add a containerized deployment?

**Comment by teleyinex** [comment]
There are a few [docker images](https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=pybossa&starCount=0), and as you can see our Circle-CI tests uses the [docker solution](https://github.com/Scifabric/pybossa/blob/master/circle.yml#L5), so we're kind of supporting Docker. We will have in the coming months hopefully an official docker image.

**Comment by BonarBeavis** [comment]
Can you give me a timeline? Because I am prototyping a [solution](https://github.com/QROWD/rdf-crowdsourced-quality-checker) for crowdsourcing linked-data quality assessment for the QROWD project. A containerized version of Pybossa for prototyping would be nice to have, for deployment it will be a must. So if you will not dockerize Pybossa in the next months, I would do it. Either way it would be nice to coordinate our efforts.

**Comment by therealmarv** [comment]
Hi @BonarBeavis . We are still in the progress of creating docker images. We will auto build them and send them to docker hub. The expected timeline is to have an alpha version till end of this year and a usable docker container version till beginning of next year. I will inform you once we have something runnable.

**Comment by cerquide** [comment]
Hi,

Taking https://github.com/jvstein/docker-compose-pybossa as guide, I have created a very simple docker-compose installer for Pybossa which works with Python 3.8. You can find it at https://github.com/cerquide/docker-compose-pybossa. This allows for a very quick installation for testing purposes. Additional work will be needed to make it into a commercial strength deployable docker structure. Anyhow, enjoy it!

**Comment by BonaBeavis** [comment]
thanks
