### ISSUE TITLE
Overall progress should be based on task runs rather than completed tasks

### ISSUE THREAD

**Issue by alexandermendes** [Scifabric/pybossa#1721]
One I noticed a long time ago (and I guess you've probably thought about it too) but the overall progress calculation is a bit misleading and should really be **task runs / (tasks * redundancy)**, instead of just counting completed tasks. Currently we could have a 100 tasks, each with 9 out of 10 required contributions and this would show 0% rather than the real answer of 90%.

**Comment by teleyinex** [comment]
This is a tough one. Let me explain you why :-)

The issue is that each task could have a different n_answers value. And this complicates everything. Especially in terms of computing the overall progress.

At the end, a project is completed when tasks are marked as completed. Therefore, we should use that metric to measure the overall progress. If a project has 100 tasks, each task has a redundancy of 10, and we have for each task 9 task_runs then, the overall progress should be 0%. We should review this for sure, but do you agree on basing this metric only on completed tasks?

We want this because we are using webhooks all the time to update the redundancy of the tasks based on the statistical analysis. Thus, using the n_answers as a metric is going to make things complicated.

**Comment by alexandermendes** [comment]
Oh yeah, I didn't consider that each task could have a different redundancy so I can see that this would make things difficult. Thanks for your detailed explanation, all makes sense!
