### ISSUE TITLE
Locking deployed tasks?

### ISSUE THREAD

**Issue by sillystring13** [Scifabric/pybossa#1781]
Currently tasks can be in the states {ongoing, completed}.  Pybossa has no notion of 'in flight' for tasks that are currently being worked.  For jobs with a redundancy=1, this means the same task can get deployed to multiple users if the task is next in line. 

Other crowd platforms such as Mechanical Turk and Crowdflower support 'in flight' with the following model:  Task is set to 'in flight' when it is served.  Two things can happen:

1. The user completes the task and the task is 'completed' normally
2. The task times out and is returned to the 'ongoing' pile to be delivered again

**Comment by sillystring13** [comment]
From what I see in the code an implementation would require
1. A third option so that task would be {ongoing, inflight, completed}
2. When a task is requested, status is set to 'inflight' and timestamps the inflight
3. When a task is completed, status is set to 'completed'
4. A scheduled clean job that checks for tasks 'inflight' for > TIMEOUT
5. Config for timeout={on,off} and timeout_interval={#minutes} with a minimum resolution (?30 minutes) such that the scheduled clean isn't constantly running

Considerations
1. Implementing a global TIMEOUT is architecturally fairly easy.  Allowing project-level timeouts looks like it would get pretty complicated.
2. Would need an example template to show UI options for timeout=on.  
      1. Timeout warning, ex "Your task will be timing out in 5 minutes, please submit to complete or you will loose your work.
      2.  Timeout event, ex "Your task is timed out, please click to request a new task"

**Comment by teleyinex** [comment]
Hi,

This is really cool :-) We have never implemented this for several reasons:

* We usually work with open problems. That means, that we don't know how long it will take to solve a problem, therefore estimating a timeout is complicated.

* Users do tasks at different paces. Forcing volunteers on a timeout could be too stressful (bear in mind that PYBOSSA does not pay volunteers as Crowdflower or Mechanical Turk).

However, PYBOSSA is here to be improved :-) Actually, we have a type of timeout already implemented to avoid trolls and scripts. In order to submit a taskrun you have to request first a task via the API. That signs the task and puts it in Redis. If this timestamp expires, then, the user will not be able to submit the task run unless he/she refreshes it.

For implementing this you could send a PR within the scheduler. Just do the migrations that you need (in case that you need them) and we will be happy to review and merge it. 

Please ask anything that you need regarding this, as we would love to help you.

PS: Regarding storing the timeout within the project: bear in mind that you have the info field in the project domain object, so you can store there whatever you need. As tasks are completely wired to projects, you will always be able to do a SQL query to get the timeout for the project, and then get the tasks for the user.

**Comment by teleyinex** [comment]
We've merged a locking scheduler. See https://docs.pybossa.com/build/project_settings/#lock
