### ISSUE TITLE
results download for the whole project

### ISSUE THREAD

**Issue by sfluo** [Scifabric/pybossa#1807]
There is a way to download results of individual tasks  from task browse.
But is there a way to download all results of one project? Should I open a issue for this?

**Comment by teleyinex** [comment]
Yes, there's. I think we might have not added the results.zip into the default theme. Can you go to the tasks section -> Export and see if there, you can see a section for Results? If there's not such a thing, then we have a bug. Can you check that?

In the meantime, you can download the results by copying the same url of the download of tasks or taskruns and change the name to *results*:

https://server/project/shortname/tasks/export?type=result&format=csv

You can get the zip file for CSV and JSON.

**Comment by sfluo** [comment]
I checked. There are export tasks and export task runs. Those are all meta data about tasks, no results included. So, that is a bug.

Thanks for the trick tip:)

**Comment by teleyinex** [comment]
Hi,

Regarding the results: results are generated empty. That's why you get the info completely empty unless you are using the webhooks solution to update it. 

We don't include the original entry in the ZIP files because we don't want to make them really large. Also, all the ZIP files come with their IDs, so you can open a spreadsheet, and load task, task_run, and results on different sheets and link them with your software. 

Also, when we do data analysis we use the PYBOSSA api which allows us to get all the results (including the related data). Please, check the following docs:

* https://docs.pybossa.com/api/crud/#related-data
* https://docs.pybossa.com/installation/configuration/#specify-a-new-root-key-instead-of-info-for-csv-exporter

**Comment by teleyinex** [comment]
[Refs](https://github.com/Scifabric/pybossa-default-theme/issues/162)

**Comment by sfluo** [comment]
​Thanks Daniel. ​see below


On Fri, Mar 2, 2018 at 7:37 AM, Daniel Lombraña González <
notifications@github.com> wrote:

> Hi,
>
> Regarding the results: results are generated empty. That's why you get the
> info completely empty unless you are using the webhooks solution to update
> it.
>
​ users have to setup their web hook in order to ​download results? Will it
be good to have a button, saying, [download project results]?

We don't include the original entry in the ZIP files because we don't want
> to make them really large. Also, all the ZIP files come with their IDs, so
> you can open a spreadsheet, and load task, task_run, and results on
> different sheets and link them with your software.
>
​Make sense!!​ Will read the docs

**Comment by teleyinex** [comment]
Regarding your first issue: it's a bug on our side and will fix it. You will be able to download the zip file, but the info field will be empty :-)

**Comment by teleyinex** [comment]
We have that ZIP file as well for task, task runs and results. Go to the export Tasks section.

Regarding export tasks: we embrace open science, so anyone should be able to download the tasks to review them if they want. Also, as PYBOSSA import CSV and JSON files, you can re-use data to re-import it to another project and build new projects.

Regarding empty ZIP files: you need to be sure that your server's background jobs are running, otherwise, it will not work.

**Comment by chrisranderson** [comment]
For some reason, none of the export links work. They just add a `#` to the URL and scroll to the top of the page.

**Comment by teleyinex** [comment]
It was an issue, that I think we fixed not so long ago. Can you check if you are running the latest pybossa-default-theme?

**Comment by chrisranderson** [comment]
@teleyinex I just pulled and restarted PyBossa, but the same thing happens.

![image](https://user-images.githubusercontent.com/5461398/39277623-eedf73e4-48ab-11e8-8db7-d1e239875359.png)

"EXPORT" just takes me to the top of the page. I would expect results from labeling to be downloaded.

**Comment by teleyinex** [comment]
Can you try the following? Type this URL in your browser and let us know if you can download a zip file:

https://YOURSERVER/project/PROJECT_SHORT_NAME/tasks/export?type=result&format=csv

That should work.

**Comment by chrisranderson** [comment]
It does download a zip, but for some reason it's empty. I'll have to check to see if I'm saving things correctly. Here's my code:

```javascript
pybossa.taskLoaded(function(task, deferred){
    this.set_image(task.info.image_url)
    this._objects = []
    this.add_turk_input_to_canvas(prepare_input_csv(task.info.data))

    submit_button.addEventListener('click', function (event) {
      data = {}
      document.querySelectorAll('input#output, textarea#comments').forEach(function (node) {
        data[node.name] = node.value
      })
      pybossa.saveTask(task.id, data).done(function() {
        deferred.resolve()
        window.location.reload(false)
      })
    }.bind(this))
  }.bind(this));

  pybossa.presentTask(function(task, deferred){
    console.log(2, task)
  }.bind(this));

  pybossa.run(window.PYBOSSA_PROJECT);
}
```

**Comment by chrisranderson** [comment]
The CSVs are empty, but it looks like things are getting saved somewhere.  I can hit http://172.23.3.175:5000/project/PROJECT_NAME/209/results.json and see what I passed to `saveTask`.

**Comment by sfluo** [comment]
Currently, if you request individual task, you will have the result. But if
you request the whole project, the answer field is empty in zip file. I
have confirmed.


---
There is no such a thing called randomness.

**Comment by teleyinex** [comment]
Yes, that behavior is expected, because the ZIP files are generated in the background. Can you check if you are running the background jobs?

**Comment by chrisranderson** [comment]
@teleyinex It's expected that when I request a ZIP with results, it's empty? Can you provide a step-by-step guide of how to get data out of pybossa? Do I need to manually run some kind of background job? Here's what my jobs look like:

![image](https://user-images.githubusercontent.com/5461398/39892895-54a39ffc-545f-11e8-8dbe-b979aca714fb.png)

The one job is one that failed a few months ago.

1. call `saveTask` with labeled data
2. ?
3. Download the CSV at `project/PROJECT_SHORT_NAME/tasks/export?type=result&format=csv`

**Comment by teleyinex** [comment]
Basically, you need to run some workers. Your workers section is completely empty, so that's why the ZIP files are not being generated. All the information regarding the background jobs is in the installation guide. Here you have the specific [section](https://docs.pybossa.com/installation/guide/#running-asynchronous-tasks-in-the-background) about it.

**Comment by teleyinex** [comment]
This was an issue with the default theme, now fixed.
