### ISSUE TITLE
User stats for users with restrict as true

### ISSUE THREAD

**Issue by dchhabda** [Scifabric/pybossa#1846]
Hi,

I was wondering whether restrict to be checked [here](https://github.com/Scifabric/pybossa/blob/master/pybossa/cache/project_stats.py#L509) as db query already filters out users with restrict as true, or whether this if condition to be "not restrict" instead. 
> if (fullname and name and not restrict) 

Thoughts?

**Comment by teleyinex** [comment]
Wait, actually, the code is fine :-) We declare them first as None, so the check is correct. In this way, we can do the testing properly (that's why I included it in such a way). Basically, I needed a way to know if the filtered users had their restrict flag set to false (instead of mocking it).

If it's clear, please, close the issue.

**Comment by dchhabda** [comment]
As db query [here](https://github.com/Scifabric/pybossa/blob/master/pybossa/cache/project_stats.py#L500) filters data by restrict=False, condition [here](https://github.com/Scifabric/pybossa/blob/master/pybossa/cache/project_stats.py#L509) will not append/add any users, right?

**Comment by teleyinex** [comment]
This is true :-) and this is a bug :-)

**Comment by dchhabda** [comment]
Thanks for confirming. Saw you fixed this under this [PR](https://github.com/Scifabric/pybossa/pull/1858)

**Comment by teleyinex** [comment]
Apologies for not getting this done earlier :-) We've been swamped with GDPR corner cases ;-)
