### ISSUE TITLE
Anonymous users not identfied as individuals

### ISSUE THREAD

**Issue by pdekker12** [Scifabric/pybossa#1887]
I run an instance of PyBOSSA, for which I would like volunteers to join anonymously (without creating an account), to lower the threshold to contribute. I was able to contribute as an anonymous user on my own pc. However, when I opened the instance to the public, anonymous contributors got the message that "All tasks have been solved".

It seems like all anonymous users (although on different devices) are seen as one user, which has already solved the tasks. Possibly the identification of IP addresses does not go well?
If I look in the task results, nearly all results contain a user_id which is a number and user_ip of None, these are probably the logged in users. One task result contains a user_id null and a user_ip with a real ip address. I have set a 32-bit cryptopan key, so I thought IP's would be hashed.

Is this a bug? Or could there be a wrong setting on my system?

**Comment by teleyinex** [comment]
Hi,

When an anonymous user contributes, we use their IP to create a hash as you have described. However, if your server is behind a proxy, you have to configure it properly, or it will be the case where all the requests will come from the same source ;-) And that's why you are probably seeing the all tasks completed for anonymous users.

For configuring the Proxy check the documentation of Nginx or the proxy you are using. You have to be sure that you are sending the original IP in the request to the PYBOSSA server, otherwise, it will not work.

You have an example [here](https://calvin.me/forward-ip-addresses-when-using-nginx-proxy/). 

If you don't have control of the Proxy, then you will need to talk to the admins to configure it properly.

**Comment by pdekker12** [comment]
Thanks a lot! Our server is indeed behind a proxy, so I will look into the IP forwarding on the proxy.

**Comment by teleyinex** [comment]
Closing it then!

**Comment by pdekker12** [comment]
With the right proxy settings, anonymous contribution is now indeed possible! However, the IP's of the anonymous users are not hashed, although I supplied a 32-character Cryptopan key. Any ideas how this could happen?
