### ISSUE TITLE
Why chose Flask ?

### ISSUE THREAD

**Issue by umaimehm** [Scifabric/pybossa#1955]
Hi,
This might sound like a dumb question but Ill ask it anyway :)

Why did you chose to use Flask for this kind of application ? Im thinking about the architecture and the use cases like image tagging, polygon drawing (future), video tagging etc are very client heavy tasks. 

Due to these use cases, I think the focus of the application should have been more on the client side and hence a technology like NodeJS would have been better.
But I might be wrong.

I am very curious to understand your thinking behind chosing python instead of a javascript framework for this project.
Thanks in advance.

**Comment by teleyinex** [comment]
Hi,

Because we built it taking into account who was using python, as this project started focused only on science projects. However, PYBOSSA is a completely headless server, so you can build all the front in anything: iOS, Android SDK, or your preferred #jamstack of choice. In our case, we use always NuxtJS for building the frontend, while the backend is our PYBOSSA solution.

All the best,

Daniel
