### ISSUE TITLE
use local imaries as tasks

### ISSUE THREAD

**Issue by TahiraU** [Scifabric/pybossa#2016]
Hi everyone,

I am new in using the pyBossa framework. Thank you for this cool service :-)! I know it isn't an issue, but I am trying to figure out how to use my local photos. The flicker example you provided only extracts the photos via URL. The `add_helpingmaterials` command is just for the tutorial but I want to use local photos for my tasks. Are there any examples I can use to build my own application, with own photos. 

Thanks in advance

**Comment by teleyinex** [comment]
Hi there,

By design, PYBOSSA does not "store the real data" but links to it. Why? Because in this way, the owner of the data decides where that data is stored, and most importantly on your own servers that you control, so PYBOSSA cannot access it directly.

Taking this into account, PYBOSSA cannot serve your images, but you can do something about it :-) You can set up an nginx server to serve your images (as you will be using PYBOSSA and Nginx as well), you don't need anything special except a config file to serve your images.

Then, create a CSV file where the links to those images are in rows. Import the CSV file, and voila, you will have your images ready within the PYBOSSA server.

You can also use something like S3 or similar to store the images and import them via a CSV file.
