### ISSUE TITLE
Clean old projects

### ISSUE THREAD

**Issue by teleyinex** [Scifabric/pybossa#927]
Now with the background jobs, there should be one that will look for old projects not updated in 3 months, send an email to the project owner warning them, that if in another month nothing happens, the project will be deleted from the system.

The email notification will include a zip file with all the information from the project, so the user can have what it was done.

**Comment by alejandrodob** [comment]
Update: ZIP creation already solved, so we can move on to the next stage.

Add a button so users can get a copy of their whole project (results, tasks, template...) which will be uploaded to a CDN (or local storage, depending on the server configuration). The email then will tell them that they can get their project before being deleted and in one month it will be anyway, unless it registers new activity.

Add an option in the admins view that allows admin to manually delete these projects. The load of them will be done as a background job, as well as the deletion. Ideally, only projects that have not had activity in a month since the warn email was sent will be displayed for deletion.

**Comment by teleyinex** [comment]
Instead of deleting projects, we will hide them with the new password solution. This is much simpler, and the project will be always there. We can then have another job that when 6 months have passed, we can safely remove it with this approach. Comments?
